### PR TITLE
Adding support for multiple devices, serial number constructor and example code

### PR DESCRIPTION
**Pull request by gordonturner**
I have been working on multiple device support and think I have a reasonable approach.

The pull request replaces the 'name' with 'serial number' as an optional constructor argument.  With multiple devices, it is likely that they will share the same name, but the serial number is unique.

Updated the readme to include the changes and added an example.js.

Let me know if you think the pull request needs enhancements?

(Also, thanks for node-xbox-controller, nice to have something to start from!)

### CODE REVIEW

**Comment by andrew** [comment]
Wonderful work @gordonturner, would you also like a commit bit so you can freely contribute to the project?

**Comment by gordonturner** [comment]
Sure, that would be great, thanks @andrew.

**Comment by andrew** [comment]
@gordonturner I've added you as a collaborator now, I'll push a new release to npm on Monday when I get home.

**Comment by gordonturner** [comment]
Hey @andrew could I bother you to push a new release to npm?

Thanks!
G.

**Comment by andrew** [comment]
Done! https://github.com/andrew/node-xbox-controller/releases/tag/v0.7.0

**Pull request merged**
